server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sb_subject_trainer
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      base-url: http://127.0.0.1:1234
      api-key: not-required
      chat:
        options:
          model: gemma3
  jpa:
    show-sql: true
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: not-required
      credentials:
        access-key: not-required
        secret-key: not-required
      s3:
        path-style-access-enabled: true
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/